### ISSUE TITLE
should refactor this cookbook to be a HWRP

### ISSUE THREAD

**Issue by jchauncey** [RallySoftware-cookbooks/datomic#10]
We should refactor this cookbook to be a HWRP. It allows it to be more extensible to users outside of Rally and it also makes it easier to test.

Acceptance Criteria -

* Includes install, start, stop, and possibly restart actions
* Allows you to download and setup datomic without actually stopping an old version and starting the new one (prepare)
* Keeps the datomic_jars style provider but refactor this code to be a method within the overall provider (instead of seperate like it is now)
* Determine how to manage users correctly (especially after the new users cookbook is done)

**Comment by ghost** [comment]
We no longer use this at Rally / CA, closing.
